repository:
  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

labels:
  - name: "breaking"
    color: ffcc00
    description: "Breaking change."
  - name: "bug"
    color: d73a4a
    description: "Something isn't working."
  - name: "dependencies"
    color: 0366d6
    description: "Pull requests that update a dependency file."
  - name: "documentation"
    color: 0075ca
    description: "Improvements or additions to documentation."
  - name: "duplicate"
    color: cfd3d7
    description: "This issue or pull request already exists."
  - name: "enhancement"
    color: a2eeef
    description: "New feature or request."
  - name: "invalid"
    color: e4e669
    description: "This doesn't seem right."
  - name: "stale"
    color: 930191
    description: "Stale issues and PRs."
  - name: "question"
    color: dd9c2c
    description: "Further information is requested."
  - name: "tests"
    color: bfd4f2
    description: "CI, CD and testing related changes."
  - name: "wontfix"
    color: ffffff
    description: "This will not be worked on."

branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before
      # merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty
        # dismissal_restrictions object to disable. User and team dismissal_restrictions
        # are only available for organization-owned repositories. Omit this parameter
        # for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable.
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch.
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to
      # enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are
      # only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
