repos:
  - repo: local
    hooks:
      - id: manifest
        name: Update manifest.json
        entry: scripts/update_manifest
        language: script
        files: ^(custom_components/.+/const\.py|requirements\.txt)$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241
    hooks:
      - id: ruff
        args:
          - --fix
        files: ^(custom_components|bin|tests)/.+\.py$
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]
        stages: [manual]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(custom_components|bin|tests)/.+\.py$
  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
          - pydocstyle==5.0.2
        files: ^(custom_components|bin|tests)/.+\.py$
        stages: [manual]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=tests/bandit.yaml
        files: ^(custom_components|bin|tests)/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        files: ^(custom_components|tests)/.+\.json$
      - id: trailing-whitespace
      # Uncomment lines below if you want to follow classical GitHub flow style development
#      - id: no-commit-to-branch
#        args:
#          - --branch=dev
  - repo: local
    hooks:
      # Run mypy through our wrapper script in order to get the possible
      # pyenv and/or virtualenv activated; it may not have been e.g. if
      # committing from a GUI tool that was not launched from an activated
      # shell.
      - id: mypy
        name: mypy
        entry: scripts/run-in-env mypy
        language: script
        types: [python]
        require_serial: true
        files: ^custom_components/.+\.py$
      - id: pylint
        name: pylint
        entry: scripts/run-in-env python3 -m pylint
        language: system
        types: [python]
      # Uncomment lines below to test code on every commit
#      - id: pytest
#        name: pytest
#        entry: scripts/run-in-env pytest
#        language: system
#        pass_filenames: false
#        always_run: true
